modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/rune-craft/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
itemIcon="runecraft:altar"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/RuneCraft.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/rune-craft"
logoFile="logo.png"
#credits=""
authors="${mod_authors}"
description='''This magical mod adds everything related to runes to the game!'''

[[mixins]]
config="mixins.${mod_id}.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${mc_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="patchouli"
type="optional"
reason="Is needed for the in-game description book, because the mod is quite complex."
versionRange="[1.20,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="bettercombat"
type="optional"
versionRange="[1.7.0+1.20,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jeed"
type="optional"
versionRange="[1.20-2.1.4,)"
ordering="NONE"
side="BOTH"
