modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/rune-craft/issues"

[[mods]]
modId="runecraft"
version="3.5.4-pre1"
displayName="RuneCraft"
itemIcon="runecraft:altar"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/RuneCraft.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/rune-craft"
logoFile="logo.png"
#credits=""
authors="XxRexRaptorxX (RexRaptor)"
description='''
This magical mod adds everything related to runes to the game!
'''

[[dependencies.runecraft]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.runecraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.runecraft]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="BOTH"
