modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/rune-craft/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
itemIcon="runecraft:altar"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/RuneCraft.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/rune-craft"
logoFile="logo.png"
#credits=""
authors="${mod_authors}"
description='''This magical mod adds everything related to runes to the game!'''


[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${mc_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="patchouli"
mandatory=false
versionRange="[1.20,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="bettercombat"
mandatory=false
versionRange="[1.7.0+1.20,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jeed"
mandatory=false
versionRange="[2.1.0,)"
ordering="NONE"
side="BOTH"
