modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/rune-craft/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
itemIcon="runecraft:altar"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/RuneCraft_NEO.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/rune-craft"
logoFile="logo.png"
#credits=""
authors="${mod_authors}"
description='''This magical mod adds everything related to runes to the game!'''

[[dependencies.${mod_id}]]
modId="neoforge"
mandatory=true
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="patchouli"
mandatory=true
type="optional"
reason="Is needed for the in-game description book, because the mod is quite complex."
versionRange="[1.21,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="bettercombat"
mandatory=false
type="optional"
versionRange="[1.7.0+1.21,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jeed"
mandatory=false
type="optional"
versionRange="[1.21-2.1.4,)"
ordering="NONE"
side="BOTH"
